source: src
destination: _site

markdown: kramdown
highlighter: rouge
incremental: true
permalink: pretty
safe: false
lsi: false

# https://kramdown.gettalong.org/options.html
# https://github.com/kramdown/parser-gfm/blob/master/lib/kramdown/parser/gfm/options.rb
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
  hard_wrap: false
  html_to_native: true
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

sass:
  sass_dir: _scss
  style: expanded

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
